name: shoplover_rider
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  dio: ^5.3.3
  connectivity_plus: ^5.0.1
  logger: ^2.0.2+1
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  shared_value: ^3.0.0
  get_storage: ^2.1.1
  country_code_picker: ^3.0.0
  shimmer: ^3.0.0

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/lottie/
    - assets/icons/

